"""
Output Formatter Module
Formats and presents results.
"""

from datetime import datetime
from src.rule_engine import ValidationResult


def format_dockerfile(content: str, validation: ValidationResult) -> str:
    """Format Dockerfile with header comments."""
    header = f"""# Generated by Production Ready Docker Intelligence Generator
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# Security: {validation.summary}

"""
    return header + content


def format_validation_report(validation: ValidationResult) -> str:
    """Format validation report."""
    report = "\n--- VALIDATION REPORT ---\n"
    
    for result in validation.results:
        symbol = '✓' if result.passed else ('⚠' if result.severity == 'WARNING' else '✗')
        report += f"{symbol} {result.rule_id}: {result.message}\n"
    
    report += f"\nSummary: {validation.summary}\n"
    return report


def add_explanatory_comments(dockerfile: str) -> str:
    """Add inline comments to Dockerfile."""
    # Already formatted with header
    return dockerfile


def generate_summary(results) -> str:
    """Generate summary of results."""
    return f"Generation complete. Validation: {results.summary if hasattr(results, 'summary') else 'N/A'}"
